### PR TITLE
PR: file absent in git, webpack crashes

### PR DESCRIPTION
**Pull request by tapy-lappy**
@AndreyAttr, there is added path.helper.js under GIT

### CODE REVIEW

**Review by AndreyAttr — APPROVED** [review]
Approved

**Review by AndreyAttr — CHANGES_REQUESTED** [review]
path.helper is ok
but what are webpack configs is doing there?

**Comment by tapy-lappy** [comment]
@AndreyAttr, It's TS transpiled them as I understood.

**Review by AndreyAttr — APPROVED** [review]

**Review by AndreyAttr — COMMENTED** [review]
If webpack files will change all the time it would be a kind of problem. For now it's ok. And it's fine if you really do changes in Webpack TS files that they are transpiled to JS. But the deal is you didn't do any changes there. And if it will continue we need to fix that.

**Comment by AndreyAttr** [comment]
**_# Merged by @AndreyAttr_**

**Pull request merged**
