### PR TITLE
https://github.com/AndreyAttr/Evo/issues/48

### PR DESCRIPTION
**Pull request by AndreyAttr**
discriminated enums(wrap enum type into wrapper with discriminant property and then use that property to distinguish what kind of enum to use - aggregate all the logic needed in one function/method)

### CODE REVIEW

**Review by tapy-lappy — COMMENTED** [review]
I commited wrong commit(wrong message), so have to revert this pull request.

**Comment by AndreyAttr** [comment]
@tapy-lappy, you can't revert the pull request which is still is not merged. Instead of that, you need to create some **fix branch** from initial(this) **angular#48 branch**(which right now contains wrong commit). Then you should switch(git checkout) to that new **fix branch**. Then do **soft reset** on **fix branch** to the right commit just before you did your wrong commit. Then you should fix wrong commit in **fix branch**, commit & push your fixes to that **fix branch**. This allows you to save all the fixes on git server and you do not loose them anyway you will do later. At the end you should merge your commited changes from **fix branch** to that initial **angular#48 branch** branch.

FYI: I recommend to do soft reset, not hard reset. Because first one save the commited changes in the files when second one kill all the logic you commited with that wrong commit. In most cases you need to do some little changes in your wrong commit to fix it instead of fully reverting your changes. And also, if smb. did changes after your wrong commit - soft reset allows you to save they changes, but hard - kill that changes too(and when you start merge your fix-branch with initial branch you will have to merge with all the commits you killed with hard reset - this can lead to merge errors).

**Comment by tapy-lappy** [comment]
Done. Merged

**Comment by tapy-lappy** [comment]
Pull request merged

**Pull request merged**
